name: documentation
on:
  push:
    branches:
    - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      # Set up dependencies
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup node
        uses: actions/setup-node@v3

      - name: Setup python
        uses: actions/setup-python@v4


      
